=== melt-umn/monto-v3-draft/content/draft02/messages/ClientBrokerNegotiation.json
{
	"$schema": "http://json-schema.org/draft-06/schema#",
	"title": "ClientBrokerNegotiation",
	"description": "The Message that a Broker sends to a Client during version negotiation.",

	"type": "object",
	"properties": {
		"monto": { "$ref": "MontoVersion.json#" },
		"broker": {
			"title": "BrokerVersion",
			"description": "The implementation and version of the Broker.",

			"type": "object",
			"properties": {
				"id": { "$ref": "Identifier.json#" },
				"name": { "type": "string" },
				"vendor": { "type": "string" },
				"major": { "type": "integer" },
				"minor": { "type": "integer" },
				"patch": { "type": "integer" }
			},
			"additionalProperties": false,
			"required": ["id"]
		},
		"extensions": {
			"title": "ClientBrokerExtensions",
			"description": "The Client Protocol extensions supported by the Broker.",

			"type": "array",
			"minItems": 1,
			"items": { "$ref": "NamespacedName.json#" },
			"uniqueItems": true
		},
		"services": {
			"title": "BrokerServices",
			"description": "The Services the Broker is connected to.",

			"type": "array",
			"items": { "$ref": "ServiceNegotiation.json#" },
			"uniqueItems": true
		}
	},
	"additionalProperties": false,
	"required": ["monto", "broker", "services"]
}

=== melt-umn/monto-v3-draft/content/draft01/messages/examples/ClientBrokerNegotiation.json
{
	"monto": {
		"major": 3,
		"minor": 0,
		"patch": 0
	},
	"broker": {
		"id": "com.acme.bar",
		"name": "Bar Broker",
		"vendor": "ACME Inc.",
		"major": 0,
		"minor": 1,
		"patch": 0
	},
	"extensions": [
		"com.acme.foo/cool_thing",
		"com.acme.bar/other_thing"
	],
	"services": [
		{
			"monto": {
				"major": 3,
				"minor": 0,
				"patch": 0
			},
			"service": {
				"id": "com.acme.quux",
				"name": "Quux Service",
				"vendor": "ACME Inc.",
				"major": 0,
				"minor": 1,
				"patch": 0
			},
			"products": []
		}
	]
}
