=== melt-umn/monto-v3-draft/content/draft02/messages/ServiceNegotiation.json
{
	"$schema": "http://json-schema.org/draft-06/schema#",
	"title": "ServiceNegotiation",
	"description": "The Message that a Service sends to a Broker during version negotiation.",

	"type": "object",
	"properties": {
		"monto": { "$ref": "ProtocolVersion.json#" },
		"service": { "$ref": "SoftwareVersion.json#" },
		"extensions": {
			"title": "ServiceExtensions",
			"description": "The Service extensions supported by the Service.",

			"type": "array",
			"minItems": 1,
			"items": { "$ref": "NamespacedName.json#" },
			"uniqueItems": true
		},
		"products": {
			"title": "BrokerProductList",
			"description": "The Products a Service can produce.",

			"type": "array",
			"items": { "$ref": "ProductIdentifier.json#" },
			"uniqueItems": true
		}
	},
	"additionalProperties": false,
	"required": ["monto", "service", "products"]
}

=== melt-umn/monto-v3-draft/content/draft01/messages/examples/ServiceNegotiation.json
{
	"monto": {
		"major": 3,
		"minor": 0,
		"patch": 0
	},
	"service": {
		"id": "com.acme.quux",
		"name": "Quux Service",
		"vendor": "ACME Inc.",
		"major": 0,
		"minor": 1,
		"patch": 0
	},
	"products": [
		{
			"name": "errors",
			"language": "python"
		},
		{
			"name": "com.acme/styleguide",
			"language": "python"
		}
	],
	"extensions": [
		"com.acme.quux/incremental"
	]
}
