=== melt-umn/monto-v3-draft/content/draft03/messages/Product.json
{
	"$schema": "http://json-schema.org/draft-06/schema#",
	"title": "Product",
	"description": "A Product, along with its contents.",

	"type": "object",
	"properties": {
		"contents": {},
		"language": { "type": "string" },
		"name": { "$ref": "ProductName.json#" },
		"meta": {
			"type": "array",
			"items": { "$ref": "#/definitions/metaItem" }
		},
		"path": { "type": "string" }
	},
	"additionalProperties": false,
	"required": ["contents", "language", "meta", "name", "path"],

	"definitions": {
		"metaItem": {
			"type": "object",
			"properties": {
				"service": { "$ref": "Identifier.json#" },
				"type": { "$ref": "#/definitions/metaType" },
				"value": { "type": "string" }
			},
			"additionalProperties": false,
			"required": ["service", "type", "value"]
		},
		"metaType": {
			"oneOf": [
				{ "const": "degraded" },
				{ "$ref": "Identifier.json#" }
			]
		}
	}
}

=== melt-umn/monto-v3-draft/draft03/messages/examples/Product.json
{
	"name": "com.example.outline",
	"language": "python",
	"path": "/foo/bar.py",
	"contents": [
		{
			"type": "function",
			"name": "main",
			"byteLocation": 80
		}
	],
	"meta": [
		{
			"service": "com.example.python_ast",
			"type": "degraded",
			"value": "Parse errors present, AST is provided on a best-effort basis"
		}
	]
}
